export const userActions = {
  ADD_NEW_USER: 'ADD_NEW_USER',
  LOGIN_USER: 'LOGIN_USER',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  LOGOUT_USER: 'LOGOUT_USER',
  GET_SIGNUP_REQUESTS: 'GET_SIGNUP_REQUESTS',
  APPROVE_SIGNUP_REQUEST: 'APPROVE_SIGNUP_REQUESTS',
  FETCH_USERS_CONTRIBUTION: 'FETCH_USERS_CONTRIBUTION'
}

export const downloadActions = {
  ADD_NEW_DOWNLOAD: 'ADD_NEW_DOWNLOAD',
  FETCH_DOWNLOADS: 'FETCH_DOWNLOADS',
  DELETE_DOWNLOAD: 'DELETE_DOWNLOAD',
  SINGLE_DOWNLOAD: 'SINGLE_DOWNLOAD',
  START_DOWNLOADS: 'START_DOWNLOADS',
  KILL_DOWNLOADS: 'KILL_DOWNLOADS'
}