export const userActions = {
  ADD_NEW_USER: 'ADD_NEW_USER',
  LOGIN_USER: 'LOGIN_USER',
  CHECK_ADMIN: 'CHECK_ADMIN',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAILURE: 'AUTH_FAILURE',
  ADD_NEW_USER_FAILED: 'ADD_NEW_USER_FAILED',
  ADD_NEW_USER_SUCCESS: 'ADD_NEW_USER_SUCCESS',
  LOGOUT_USER: 'LOGOUT_USER',
  GET_SIGNUP_REQUESTS: 'GET_SIGNUP_REQUESTS',
  APPROVE_SIGNUP_REQUEST: 'APPROVE_SIGNUP_REQUESTS',
  APPROVE_SIGNUP_REQUEST_SUCCESS: 'APPROVE_SIGNUP_REQUEST_SUCCESS',
  APPROVE_SIGNUP_REQUEST_FAILED: 'APPROVE_SIGNUP_REQUEST_FAILED',
  FETCH_USERS_CONTRIBUTION: 'FETCH_USERS_CONTRIBUTION'
};

export const downloadActions = {
  ADD_NEW_DOWNLOAD: 'ADD_NEW_DOWNLOAD',
  FETCH_DOWNLOADS: 'FETCH_DOWNLOADS',
  FETCH_DOWNLOADS_FAILED: 'FETCH_DOWNLOADS_FAILED',
  FAILED_ADDING_DOWNLOAD: 'FAILED_ADDING_DOWNLOAD',
  DELETE_DOWNLOAD: 'DELETE_DOWNLOAD',
  SINGLE_DOWNLOAD: 'SINGLE_DOWNLOAD',
  START_DOWNLOADS: 'START_DOWNLOADS',
  KILL_DOWNLOADS: 'KILL_DOWNLOADS'
};
