#!/bin/bash
echo "Preparing to install Bassa..."

yes | pacman -Syu

echo "Installing pip"
yes | pacman -S python-pip
echo "pip installed"

echo "Installing setuptools"
yes | pacman -S python-setuptools
echo "pip installed"

echo "Installing Aria2"
yes | pacman -S aria2
echo "Aria2 installed"

echo "Installing mysql-server"
pacman -S mysql
echo "mysql-server installed"

echo "Installing libmysqlclient"
yes | pacman -S libmysqlclient
echo "libmysqlclient installed"

echo "Installing node"
curl -sL https://deb.nodesource.com/setup_6.x | -E bash -
echo "NodeJS installed"

echo "Installing bower globally"
npm install -g bower
echo "bower installed"

echo "Installing gulp globally"
npm install -g gulp
echo "gulp installed"

echo "Finshed installing required components !"
