kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ include "bassa-api.fullname" . }}-{{ .Values.persistentVolume.name }}-claim"
spec:
  accessModes:
    - {{ .Values.persistentVolume.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage }}
