kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: api
  namespace: bassa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      volumes:
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads-claim  
      containers:
      - name: api
        image: kmehant/api
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: BASSA_DB_NAME
          value: 'Bassa'
        - name: BASSA_DB_USERNAME
          value: 'bassa'
        - name: BASSA_DB_PASSWORD
          value: 'bassa@1234'
        volumeMounts:
        - mountPath: /downloads
          name: downloads
      - name: aria2c
        image: kmehant/aria2c
        imagePullPolicy: Always
        ports:
        - containerPort: 6800
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: downloads
      restartPolicy: Always