FROM node:7

MAINTAINER SCoRe Lab Community <commuity@scorelab.org>

ARG BUILD_DATE
ARG VCS_REF

WORKDIR /ui

# Copying UI contents into container
COPY . .

# Exposing port for accessing the web interface 
EXPOSE 3000

# Installing node modules and bower modules
RUN apt-get update && \ 
    npm install && \
    npm install --global bower gulp-cli && \
    bower --allow-root install

# Starting gulp server
CMD ["gulp", "serve"]

# labels to dockerfile
LABEL scorelab.bassa.name="Bassa Web development server" \
      scorelab.bassa.description="Dockerfile for Bassa Web" \
      scorelab.bassa.url="https://github.com/scorelab/Bassa/wiki" \
      scorelab.bassa.vcs-url="https://github.com/scorelab/Bassa" \
      scorelab.bassa.vcs-ref=$VCS_REF \
      scorelab.bassa.build-date=$BUILD_DATE \
      scorelab.bassa.vendor="Sustainable Computing Research Group" \
      scorelab.bassa.version="1.0" \
      scorelab.bassa.schema-version="1.0"
